prompts:
  summarize:
    defaults:
      tone: concise
      audience: general
      bullets_min: 4
      bullets_max: 6
    clients:
      acme:
        tone: detailed
        audience: executives
        bullets_min: 5
        bullets_max: 7
      demo:
        tone: friendly
        audience: product managers