# 🚀 Unified Content Creator System - Complete Configuration
# This file contains all configuration for the complete system including:
# - Core content generation tools (HTML, DOC, PPT, PDF)
# - Image and icon generation tools
# - MCP server ecosystem
# - Research integration, content validation, and advanced orchestration

# System Configuration
system:
  name: "Unified Content Creator System"
  version: "2.0.0"
  description: "Complete content creation platform with AI-powered planning, research, and generation"
  environment: "production"
  debug: false
  log_level: "INFO"

# Core Content Generation Tools
content_generation:
  enhanced_ppt_generator:
    enabled: true
    api_key_env: "PRESENTON_API_KEY"
    default_model: "gpt-4o"
    max_tokens: 2000
    temperature: 0.2
    supported_formats: ["pptx"]
    templates: ["professional", "creative", "modern", "classic", "minimalist"]
    include_images: true
    include_icons: true
    max_slides: 50
    
  enhanced_document_generator:
    enabled: true
    default_format: "docx"
    supported_formats: ["docx", "pdf", "html", "md", "tex", "rtf"]
    templates: ["professional", "academic", "creative", "minimalist", "corporate"]
    languages: ["en", "es", "fr", "de", "zh", "ja", "ar"]
    css_frameworks: ["tailwind", "bootstrap", "bulma", "foundation", "custom"]
    pandoc:
      enabled: true
      path: "pandoc"
      timeout: 60
    weasyprint:
      enabled: true
      timeout: 45
    reportlab:
      enabled: true
      timeout: 30
      
  enhanced_image_generator:
    enabled: true
    providers:
      unsplash:
        enabled: true
        api_key_env: "UNSPLASH_API_KEY"
        timeout: 30
        max_images: 10
      stable_diffusion:
        enabled: true
        api_key_env: "STABLE_DIFFUSION_API_KEY"
        timeout: 60
        max_images: 5
      pixabay:
        enabled: true
        api_key_env: "PIXABAY_API_KEY"
        timeout: 30
        max_images: 10
    supported_formats: ["jpeg", "png", "webp", "svg"]
    quality_levels: ["low", "medium", "high"]
    size_presets: ["small", "medium", "large", "custom"]
    
  enhanced_icon_generator:
    enabled: true
    providers:
      iconify:
        enabled: true
        timeout: 20
        max_icons: 5
      lucide:
        enabled: true
        timeout: 15
        max_icons: 5
      custom_ai:
        enabled: true
        api_key_env: "OPENAI_API_KEY"
        timeout: 30
        max_icons: 3
    supported_formats: ["svg", "png", "ico", "webp"]
    size_presets: ["small", "medium", "large"]

# MCP Server Ecosystem
mcp_servers:
  sequential_thinking:
    url: "http://localhost:3001"
    timeout: 60
    retry_attempts: 3
    health_check: true
    description: "AI-powered content planning and structuring"
    features:
      - content_analysis
      - structure_planning
      - content_structuring
      - validation
      - optimization
    
  brave_search:
    url: "http://localhost:3002"
    enabled: true
    timeout: 30
    max_results: 10
    safe_search: true
    region: "US"
    description: "Web search and content research capabilities"
    features:
      - web_search
      - news_search
      - image_search
      - result_filtering
    
  memory:
    url: "http://localhost:3003"
    timeout: 30
    max_context_size: "10MB"
    retention_days: 30
    description: "Content storage and retrieval system"
    features:
      - content_storage
      - context_retrieval
      - metadata_indexing
      - cleanup_automation
    
  filesystem:
    url: "http://localhost:3004"
    timeout: 30
    base_path: "./output"
    max_file_size: "100MB"
    description: "File operations and management"
    features:
      - file_operations
      - directory_management
      - metadata_tracking
      - safety_checks
    
  image_generation:
    url: "http://localhost:3005"
    enabled: true
    timeout: 60
    max_images_per_request: 10
    supported_formats: ["jpeg", "png", "webp", "svg"]
    description: "Multi-provider image generation"
    
  icon_generation:
    url: "http://localhost:3006"
    enabled: true
    timeout: 45
    max_icons_per_request: 5
    supported_formats: ["svg", "png", "ico", "webp"]
    description: "Multi-provider icon generation"

# Research Integration Configuration
research_integration:
  enabled: true
  default_depth: "moderate"
  max_results: 10
  cache_ttl: 3600
  patterns:
    presentation:
      keywords: ["trends", "statistics", "case studies", "best practices", "industry insights"]
      content_types: ["article", "news", "academic", "government"]
      min_credibility: 0.7
    document:
      keywords: ["research", "data", "analysis", "reports", "studies"]
      content_types: ["academic", "government", "research", "industry"]
      min_credibility: 0.8
    html:
      keywords: ["web content", "digital trends", "user experience", "design patterns"]
      content_types: ["blog", "article", "tutorial", "guide"]
      min_credibility: 0.6
  filtering:
    min_relevance: 0.6
    min_credibility: 0.5
    max_age_days: 365
    exclude_domains: ["spam.com", "fake-news.com"]
    include_domains: []

# Content Validation Configuration
content_validation:
  enabled: true
  rules:
    readability:
      enabled: true
      threshold: 0.7
      severity: "warning"
      target_audience: "Grade 8-10"
    seo:
      enabled: true
      threshold: 0.6
      severity: "info"
      check_keywords: true
      check_meta_tags: true
    accessibility:
      enabled: true
      threshold: 0.8
      severity: "warning"
      wcag_level: "AA"
    grammar:
      enabled: true
      threshold: 0.9
      severity: "error"
      language: "en"
    plagiarism:
      enabled: true
      threshold: 0.95
      severity: "error"
      check_sources: true
  metrics:
    word_count: true
    sentence_count: true
    paragraph_count: true
    reading_time: true
    complexity_score: true
    keyword_density: true

# Advanced Orchestration Configuration
advanced_orchestration:
  enabled: true
  max_workflow_steps: 50
  max_workflow_duration: 3600
  default_timeout: 300
  max_retries: 3
  retry_delay: 5
  workflow_types:
    action: true
    decision: true
    parallel: true
    loop: true
    condition: true
  execution:
    background_processing: true
    parallel_execution: true
    progress_tracking: true
    status_monitoring: true
    execution_history: true
  default_workflows:
    content_creation:
      enabled: true
      name: "Content Creation Workflow"
      description: "Complete workflow for content creation with research and validation"
      steps: 7
      conditions: 1
    research_enhancement:
      enabled: true
      name: "Research Enhancement Workflow"
      description: "Automated research and content enhancement workflow"
      steps: 5
      conditions: 2

# Unified Content Creator Configuration
unified_content_creator:
  enabled: true
  default_output_format: "presentation"
  supported_formats: ["presentation", "document", "pdf", "html"]
  content_styles: ["professional", "creative", "modern", "classic", "minimalist"]
  languages: ["English", "Spanish", "French", "German", "Chinese", "Japanese", "Arabic"]
  themes: ["auto", "light", "dark", "custom"]
  features:
    include_images: true
    include_icons: true
    include_research: true
    include_validation: true
    include_orchestration: true
  workflow:
    planning_enabled: true
    research_enabled: true
    generation_enabled: true
    validation_enabled: true
    storage_enabled: true

# API Configuration
api:
  server:
    host: "0.0.0.0"
    port: 8000
    workers: 4
    timeout: 120
    max_requests: 1000
    cors_enabled: true
    rate_limiting:
      enabled: true
      requests_per_minute: 60
      burst_size: 10
  
  endpoints:
    enhanced_ppt: "/api/v1/ppt"
    enhanced_document: "/api/v1/document"
    enhanced_image: "/api/v1/image"
    enhanced_icon: "/api/v1/icon"
    unified_content: "/api/v1/content"
    unified_system: "/api/v1/unified"
    mcp_sequential_thinking: "/api/v1/mcp/sequential-thinking"
    mcp_brave_search: "/api/v1/mcp/brave-search"
    mcp_memory: "/api/v1/mcp/memory"
    mcp_filesystem: "/api/v1/mcp/filesystem"
    mcp_research_integration: "/api/v1/mcp/research"
    mcp_content_validation: "/api/v1/mcp/validation"
    mcp_advanced_orchestration: "/api/v1/mcp/orchestration"

# Storage Configuration
storage:
  output_directory: "./output"
  temp_directory: "./temp"
  cache_directory: "./cache"
  max_file_size: "100MB"
  cleanup:
    enabled: true
    interval_hours: 24
    max_age_days: 7
    max_total_size: "1GB"
  
  databases:
    sqlite:
      enabled: true
      path: "./data/unified_system.db"
      backup_enabled: true
      backup_interval_hours: 12
    redis:
      enabled: false
      host: "localhost"
      port: 6379
      db: 0

# Monitoring and Logging
monitoring:
  enabled: true
  metrics:
    performance: true
    errors: true
    usage: true
    health: true
  
  logging:
    level: "INFO"
    format: "json"
    rotation: "daily"
    retention: "30 days"
    file_path: "./logs/unified_system.log"
  
  health_checks:
    enabled: true
    interval_seconds: 30
    timeout_seconds: 10
    endpoints:
      - "/health"
      - "/ready"
      - "/metrics"

# Security Configuration
security:
  authentication:
    enabled: false
    type: "api_key"
    api_key_env: "API_KEY"
  
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
  
  input_validation:
    enabled: true
    max_content_length: "10MB"
    allowed_file_types: ["txt", "md", "html", "docx", "pptx"]
    sanitize_input: true
  
  output_validation:
    enabled: true
    scan_for_malware: false
    validate_file_integrity: true

# Performance Configuration
performance:
  caching:
    enabled: true
    ttl_seconds: 3600
    max_size: "100MB"
  
  async:
    enabled: true
    max_concurrent_requests: 50
    timeout_seconds: 120
  
  optimization:
    template_caching: true
    static_file_serving: true
    compression: true
    minification: false

# Deployment Configuration
deployment:
  docker:
    enabled: true
    base_image: "python:3.11-slim"
    multi_stage: true
    optimize_layers: true
  
  cloud_run:
    enabled: true
    region: "us-central1"
    cpu: "1"
    memory: "2Gi"
    max_instances: 10
    timeout_seconds: 300
  
  kubernetes:
    enabled: false
    namespace: "unified-content"
    replicas: 3
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"

# Testing Configuration
testing:
  enabled: true
  frameworks:
    pytest: true
    unittest: false
  
  coverage:
    enabled: true
    threshold: 80
    exclude_patterns:
      - "tests/*"
      - "scripts/*"
      - "docs/*"
  
  integration_tests:
    enabled: true
    timeout_seconds: 300
    parallel: true
  
  performance_tests:
    enabled: true
    load_test_duration: 60
    concurrent_users: 10

# Environment Variables
environment:
  required:
    - "OPENAI_API_KEY"
    - "ANTHROPIC_API_KEY"
    - "GOOGLE_API_KEY"
  
  optional:
    - "PRESENTON_API_KEY"
    - "UNSPLASH_API_KEY"
    - "STABLE_DIFFUSION_API_KEY"
    - "PIXABAY_API_KEY"
    - "BRAVE_SEARCH_API_KEY"
    - "API_KEY"
  
  defaults:
    LOG_LEVEL: "INFO"
    DEBUG: "false"
    ENVIRONMENT: "development"
    PORT: "8000"
    HOST: "0.0.0.0"
